config/routes.rb
Rails.application.routes.draw do

  resources :programmes
  resources :colleges
  resources :faculties
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    #root 'devise/sessions#new'
    get '/customers/:id', :to => 'customers#show', as: 'customer'
    get '/agents/:id', :to => 'agents#show', as: 'agent'
  end

  resources :documents, :applications, :institutions

  get 'dashboard' => 'dashboard#index'
  get 'agents' => 'agents#index'
  get 'customers' => 'customers#index'
  get 'pending' => 'applications#pending'


  root to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :application_documents
  has_many :documents, through: :application_documents
  belongs_to :user
  belongs_to :institution
  has_one :college
  validates :firstname, :lastname, :dob, :enrolled, :completed,
  			:quantity, :department, :phone, :institution_id,
        :programme, :address, :reason, :presence => true

  has_attached_file :student_id, :styles => { :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :student_id, :content_type => /\Aimage\/.*\Z/

  has_attached_file :acceptance_letter, :styles => { :thumb => "150x150>" },  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :acceptance_letter, :content_type => /\Aimage\/.*\Z/

  geocoded_by :full_address

  after_validation :geocode, :latitude, :longitude

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_address
    address
  end


end

app/models/application_document.rb
class ApplicationDocument < ApplicationRecord
  belongs_to :document
  belongs_to :application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/document.rb
class Document < ApplicationRecord
  has_many :application_documents
  has_many :applications, through: :application_documents
end

app/models/faculty.rb
class Faculty < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :applications
    has_many :faculties, dependent: :destroy
    has_many :colleges, dependent: :destroy
    has_many :programmes, :through => :faculties
    has_many :programmes, through: :colleges

    validates_presence_of :name


end

app/models/programme.rb
class Programme < ApplicationRecord
    belongs_to :faculty
    belongs_to :college

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications

  # validates :username, presence: true, uniqueness: true
  # validates :firstname, :lastname, presence: true
  # validates :phone, presence: true, numericality: true
  # validates :email, presence: true, uniqueness: true
  # validates :password, presence: true, confirmation: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to applications_path
  	end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
  def switch_key(key)
    keys = {
      'alert' => 'negative',
      'notice' => 'olive',
      'success' => 'info'
    }
    keys[key]
  end
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/layouts/shared/_notice.html.erb
<% require_relative '../../../helpers/notice_helper.rb' %>
<% flash.each do |key, value| %>
     <div class="ui message <%= switch_key(key) %>">
       <i class="close icon"></i>
        <p> <%= value %></p>
     </div>
<% end %>

app/views/layouts/shared/_sidebar.html.erb
    <div class="ui grid">
      <div class="row">

          <div class="column" id="sidebar">
          <div class="ui secondary vertical fluid pointing menu">
            <%=link_to '<i class="chart line icon"></i>Dashboard'.html_safe, dashboard_path, class: "item" %>
            <%=link_to '<i class="folder open icon"></i>All Requests'.html_safe, applications_path, class: "item" %>
            <%=link_to '<i class="sync alternate icon"></i>Pending Requests'.html_safe, pending_path, class: "item" %>



            <div class="ui hidden divider"></div>

            <% if current_user.admin? %>
              <%=link_to '<i class="user secret icon"></i>Agents'.html_safe, agents_path, class: "item" %>
              <%#=link_to '<i class="users icon"></i>Customers'.html_safe, customers_path, class: "item" %>
              <%=link_to '<i class="home icon"></i>Institutions'.html_safe, institutions_path, class: "item" %>
              <%=link_to '<i class="file alternate icon"></i>Documents'.html_safe, documents_path, class: "item" %>
              <%=link_to '<i class="building icon"></i>Faculties'.html_safe, faculties_path, class: "item" %>
              <%=link_to '<i class="warehouse icon"></i>Colleges'.html_safe, colleges_path, class: "item" %>
            <% end %>

          </div>
        </div>