config/routes.rb
Rails.application.routes.draw do

  resources :programmes
  resources :colleges
  resources :faculties
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    #root 'devise/sessions#new'
    get '/customers/:id', :to => 'customers#show', as: 'customer'
    get '/agents/:id', :to => 'agents#show', as: 'agent'
  end

  resources :documents, :applications, :institutions

  get 'dashboard' => 'dashboard#index'
  get 'agents' => 'agents#index'
  get 'customers' => 'customers#index'
  get 'pending' => 'applications#pending'


  root to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :application_documents
  has_many :documents, through: :application_documents
  belongs_to :user
  belongs_to :institution
  has_one :college
  validates :firstname, :lastname, :dob, :enrolled, :completed,
  			:quantity, :department, :phone, :institution_id,
        :programme, :address, :reason, :presence => true

  has_attached_file :student_id, :styles => { :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :student_id, :content_type => /\Aimage\/.*\Z/

  has_attached_file :acceptance_letter, :styles => { :thumb => "150x150>" },  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :acceptance_letter, :content_type => /\Aimage\/.*\Z/

  geocoded_by :full_address

  after_validation :geocode, :latitude, :longitude

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_address
    address
  end


end

app/models/application_document.rb
class ApplicationDocument < ApplicationRecord
  belongs_to :document
  belongs_to :application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/document.rb
class Document < ApplicationRecord
  has_many :application_documents
  has_many :applications, through: :application_documents
end

app/models/faculty.rb
class Faculty < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :applications
    has_many :faculties, dependent: :destroy
    has_many :colleges, dependent: :destroy
    has_many :programmes, :through => :faculties
    has_many :programmes, through: :colleges

    validates_presence_of :name


end

app/models/programme.rb
class Programme < ApplicationRecord
    belongs_to :faculty
    belongs_to :college

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications

  # validates :username, presence: true, uniqueness: true
  # validates :firstname, :lastname, presence: true
  # validates :phone, presence: true, numericality: true
  # validates :email, presence: true, uniqueness: true
  # validates :password, presence: true, confirmation: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :set_customer, only: [:show, :edit, :update, :destroy] 

    def index
        @customers = User.where("users.admin = ? and users.agent = ? ", false, false)
    end

    

    def show
    end


    private
      def set_customer
        @customer = User.find(params[:id])
      end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to applications_path
  	end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
  def switch_key(key)
    keys = {
      'alert' => 'negative',
      'notice' => 'olive',
      'success' => 'info'
    }
    keys[key]
  end
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/customers/index.html.erb
<%= render :partial => "layouts/shared/sidebar" %>

<div class="column" id="content">
  <div class="ui grid">
  <%= render :partial => "layouts/shared/notice"%>
    <div class="row">
      <h1 class="ui huge header">
        Customers
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">
      <table class="ui single line striped selectable table">
        <thead>
          <tr>
            <th>Customer Name</th>
            <th>Customer Username</th>
            <th>Customer Phone</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.try(:firstname) + ' ' + customer.try(:lastname) %></td>
              <td><%= customer.try(:username) %></td>
              <td><%= customer.phone %></td>
              <td><%= link_to '<i class="eye icon"></i>View'.html_safe, customer_path(customer), class: "ui basic button" %></td>
              <% if current_user.admin? %>
                <td><%#= link_to '<i class="edit outline icon"></i>Edit'.html_safe, edit_document_path(customer), class: "ui basic button" %></td>
                <td><%#= link_to '<i class="trash icon"></i>Delete'.html_safe, customer, method: :delete, data: { confirm: 'Are you sure?' }, class: "negative ui button" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

<br>


<% if current_user.admin?%>
  <%= link_to '<i class="plus circle icon"></i>Add Customer'.html_safe, '#', class: "positive large ui button item"  %>
<% end %>

app/views/customers/show.html.erb
<%= render :partial => "layouts/shared/sidebar" %>
<div class="column" id="content">
  <div class="ui ">
    <%= render :partial => "layouts/shared/notice" %>
    <div class="row">
      <h1 class="ui huge header">
        View Customer
      </h1>
    </div>
    <div class="ui divider"></div>
    <br />

    <div class="item">
      <strong>Username:</strong>
      <%=  @customer.username  %>
    </div>

    <div class="item">
      <strong>Full Name:</strong>
      <%= @customer.try(:firstname) + ' ' + @customer.try(:lastname) %>
    </div>

    <div class="item">
      <strong>Email:</strong>
      <%= @customer.email %>
    </div>

    <div class="item">
      <strong>Phone:</strong>
      <%= @customer.phone %>
    </div>

    <div class="item">
      <strong>Sign Up Date:</strong>
      <%= @customer.created_at %>
    </div>

    <div class="item">
      <strong>Last Sign In Date:</strong>
      <%= @customer.last_sign_in_at %>
    </div>

    <div class="item">
      <strong>Number of Requests:</strong>
      <%= @customer.applications.count %>
    </div>

    <div class="item">
      <strong>Number of Pending Requests:</strong>
      <%= @customer.applications.where(processed: false).count %>
    </div>

     <div class="item">
      <strong>Number of Delivered Requests:</strong>
      <%= @customer.applications.where(delivered: true).count %>
    </div>



    <br />
<% if current_user.admin? %>
  <%#= link_to 'Edit Institution', edit_institution_path(@institution), class: "ui large button" %> |
<% end %>
<%= link_to 'All Customers', customers_path, class: "ui large button" %>