config/routes.rb
Rails.application.routes.draw do

  resources :programmes
  resources :colleges
  resources :faculties
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    #root 'devise/sessions#new'
    get '/customers/:id', :to => 'customers#show', as: 'customer'
    get '/agents/:id', :to => 'agents#show', as: 'agent'
  end

  resources :documents, :applications, :institutions

  get 'dashboard' => 'dashboard#index'
  get 'agents' => 'agents#index'
  get 'customers' => 'customers#index'
  get 'pending' => 'applications#pending'


  root to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :application_documents
  has_many :documents, through: :application_documents
  belongs_to :user
  belongs_to :institution
  has_one :college
  validates :firstname, :lastname, :dob, :enrolled, :completed,
  			:quantity, :department, :phone, :institution_id,
        :programme, :address, :reason, :presence => true

  has_attached_file :student_id, :styles => { :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :student_id, :content_type => /\Aimage\/.*\Z/

  has_attached_file :acceptance_letter, :styles => { :thumb => "150x150>" },  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :acceptance_letter, :content_type => /\Aimage\/.*\Z/

  geocoded_by :full_address

  after_validation :geocode, :latitude, :longitude

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_address
    address
  end


end

app/models/application_document.rb
class ApplicationDocument < ApplicationRecord
  belongs_to :document
  belongs_to :application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/applications_document.rb
class ApplicationsDocument < ApplicationRecord
  belongs_to :document
  belongs_to :application
end

app/models/college.rb
class College < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/document.rb
class Document < ApplicationRecord
  has_many :application_documents
  has_many :applications, through: :application_documents
end

app/models/faculty.rb
class Faculty < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :applications
    has_many :faculties, dependent: :destroy
    has_many :colleges, dependent: :destroy
    has_many :programmes, :through => :faculties
    has_many :programmes, through: :colleges

    validates_presence_of :name


end

app/models/programme.rb
class Programme < ApplicationRecord
    belongs_to :faculty
    belongs_to :college

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications

  # validates :username, presence: true, uniqueness: true
  # validates :firstname, :lastname, presence: true
  # validates :phone, presence: true, numericality: true
  # validates :email, presence: true, uniqueness: true
  # validates :password, presence: true, confirmation: true
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = User.where(agent: true)
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = User.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = User.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      #params.fetch(:agent, {})

      params.require(:application).permit(:firstname, :lastname, :username, :email)

    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    flash.now[:success] = "We currently have #{@documents.size} "\
                          "types of documents available!"
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, success: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, success: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, success: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to applications_path
  	end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
  def switch_key(key)
    keys = {
      'alert' => 'negative',
      'notice' => 'olive',
      'success' => 'info'
    }
    keys[key]
  end
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/documents/_document.html.erb
<div class="badge">
  <ul>
    <li><%= document.name %></li>
  </ul>
  <%#= link_to document.name, document_path(document) %> &nbsp;
</div>

app/views/documents/_form.html.erb
<div class="container">

  <div class="row">


    <%= form_with(model: document, local: true) do |form| %>
      <% if document.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

          <ul>
          <% document.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

       <div class="ui large form">
          <div class='equal width fields'>

            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, id: :document_name %>
            </div>

          </div>
        </div>  

        <%= form.submit 'Submit Document', :class => "ui submit button primary large" %>
        
    <% end %>

app/views/documents/edit.html.erb
<%= render :partial => "layouts/shared/sidebar" %>
<div class="column" id="content">
  <div class="ui grid">
    <%= render :partial => "layouts/shared/notice" %>
 
    <div class="row">
      <h1 class="ui huge header">
        Editing Document 
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">
        <%= render 'form', document: @document %>
    </div>
  </div>
</div>

<%= link_to 'View Document', @document, class: "ui basic button"  %> |
<%= link_to 'All Documents', documents_path, class: "ui basic button"  %>

app/views/documents/index.html.erb
<%= render :partial => "layouts/shared/sidebar" %>

<div class="column" id="content">
  <div class="ui grid">
  <%= render :partial => "layouts/shared/notice"%>
    
    <div class="row">
      <h1 class="ui huge header">
        Documents
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">
      <table class="ui single line striped selectable table">
        <thead>
          <tr>
            <th>Document Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @documents.each do |document| %>
            <tr>
              <td><%= document.name %></td>
              <td><%= link_to '<i class="eye icon"></i>View'.html_safe, document, class: "ui basic button" %></td>
              <% if current_user.admin? %>
                <td><%= link_to '<i class="edit outline icon"></i>Edit'.html_safe, edit_document_path(document), class: "ui basic button" %></td>
                <td><%= link_to '<i class="trash icon"></i>Delete'.html_safe, document, method: :delete, data: { confirm: 'Are you sure?' }, class: "negative ui button" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

<br>


<% if current_user.admin?%>
  <%= link_to '<i class="plus circle icon"></i>Add Document'.html_safe, new_document_path, class: "positive large ui button item"  %>
<% end %>

app/views/documents/new.html.erb
<%= render :partial => "layouts/shared/sidebar" %>

<div class="container" id="content">
  <div class="ui grid">
    <%= render :partial => "layouts/shared/notice"%>

    <div class="row">
      <h1 class="ui huge header">
        Create A New Document 
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">
        <%= render 'form', document: @document %>
    </div>

    </div>
</div>

<%#= link_to 'All Documents', documents_path, class: "ui basic button"  %>

app/views/documents/show.html.erb
<%= render :partial => "layouts/shared/sidebar" %>
<div class="column" id="content">
  <div class="ui ">
    <%= render :partial => "layouts/shared/notice" %>
    <!--<div class="ui divider"></div>-->
    
    <!-- <div class="ui hidden section divider"></div> -->
    <div class="row">
      <h1 class="ui huge header">
        View Document
      </h1>
    </div>
    <div class="ui divider"></div>

    <br />

    <div class="item">
      <strong>Document Name:</strong>
      <%= @document.name %>
    </div>

    <br />

    <% if current_user.admin? %>
      <%= link_to 'Edit', edit_document_path(@document), class: "ui large button"  %> |
    <% end %>
    <%= link_to 'Back', documents_path, class: "ui large button"  %>
</div>