config/routes.rb
Rails.application.routes.draw do

  resources :programmes
  resources :colleges
  resources :faculties
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    #root 'devise/sessions#new'
    get '/customers/:id', :to => 'customers#show', as: 'customer'
    get '/agents/:id', :to => 'agents#show', as: 'agent'
  end

  resources :documents, :applications, :institutions

  get 'dashboard' => 'dashboard#index'
  get 'agents' => 'agents#index'
  get 'customers' => 'customers#index'
  get 'pending' => 'applications#pending'


  root to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :application_documents
  has_many :documents, through: :application_documents
  belongs_to :user
  belongs_to :institution
  has_one :college
  validates :firstname, :lastname, :dob, :enrolled, :completed,
  			:quantity, :department, :phone, :institution_id,
        :programme, :address, :reason, :presence => true

  has_attached_file :student_id, :styles => { :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :student_id, :content_type => /\Aimage\/.*\Z/

  has_attached_file :acceptance_letter, :styles => { :thumb => "150x150>" },  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :acceptance_letter, :content_type => /\Aimage\/.*\Z/

  geocoded_by :full_address

  after_validation :geocode, :latitude, :longitude

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_address
    address
  end


end

app/models/application_document.rb
class ApplicationDocument < ApplicationRecord
  belongs_to :document
  belongs_to :application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/applications_document.rb
class ApplicationsDocument < ApplicationRecord
  belongs_to :document
  belongs_to :application
end

app/models/college.rb
class College < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/document.rb
class Document < ApplicationRecord
  has_many :application_documents
  has_many :applications, through: :application_documents
end

app/models/faculty.rb
class Faculty < ApplicationRecord
    belongs_to :institution

    validates_presence_of :name

    def mother_institution(institution_id)
        Institution.find(institution_id).name
    end

end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :applications
    has_many :faculties, dependent: :destroy
    has_many :colleges, dependent: :destroy
    has_many :programmes, :through => :faculties
    has_many :programmes, through: :colleges

    validates_presence_of :name


end

app/models/programme.rb
class Programme < ApplicationRecord
    belongs_to :faculty
    belongs_to :college

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications

  # validates :username, presence: true, uniqueness: true
  # validates :firstname, :lastname, presence: true
  # validates :phone, presence: true, numericality: true
  # validates :email, presence: true, uniqueness: true
  # validates :password, presence: true, confirmation: true
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = User.where(agent: true)
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = User.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = User.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      #params.fetch(:agent, {})

      params.require(:application).permit(:firstname, :lastname, :username, :email)

    end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :institution_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to applications_path
  	end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
  def switch_key(key)
    keys = {
      'alert' => 'negative',
      'notice' => 'olive',
      'success' => 'info'
    }
    keys[key]
  end
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/colleges/_form.html.erb
<div class="container">

  <div class="row">


<%= form_with(model: college, local: true) do |form| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <div class="ui large form">
          <div class='equal width fields'>

            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, id: :college_name, :class => 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :institution_id %>
              <%= form.collection_select(:institution_id, Institution.all, :id, :name, :class => 'form-control') %>
            </div>


            

          </div>
            <%= form.submit 'Submit College', :class => "ui submit button primary large" %>
        </div>
<% end %>

app/views/colleges/edit.html.erb
<%= render :partial => "layouts/shared/sidebar" %>
<div class="column" id="content">
  <div class="ui grid">
    <%= render :partial => "layouts/shared/notice" %>
    <div class="row">
      <h1 class="ui huge header">
        Editing College 
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">

        <%= render 'form', college: @college %>

    </div>
  </div>
</div>

<%= link_to 'View College', @college, class: "ui basic button" %> |
<%= link_to 'All Colleges', colleges_path, class: "ui basic button" %>

app/views/colleges/index.html.erb
<%= render :partial => "layouts/shared/sidebar" %>

<div class="column" id="content">
  <div class="ui grid">
  <%= render :partial => "layouts/shared/notice"%>
    <div class="row">
      <h1 class="ui huge header">
        All Colleges
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">
    <table class="ui single line striped selectable table">
      <thead>
        <tr>
          <th>
            Name
          </th>
         
          <th>
            Name of Institution
          </th>

          <th colspan="3">
            
          </th>
        </tr>
      </thead>
      
      <tbody>
        <% @colleges.each do |college| %>
          <tr>
            <td><%= college.name %></td>
            <td><%= college.mother_institution(college.institution_id) %></td>
            <td><%= link_to '<i class="eye icon"></i>View'.html_safe, college, class: "ui basic button" %></td>
            <td><%= link_to '<i class="edit outline icon"></i>Edit'.html_safe, edit_college_path(college), class: "ui basic button" %></td>
            <td><%= link_to '<i class="trash icon"></i>Delete'.html_safe, college, method: :delete, data: { confirm: 'Are you sure?' }, class: "negative ui button" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>


<br>

<%= link_to '<i class="plus circle icon"></i>New College'.html_safe, new_college_path, class: "positive ui button" %>



     

app/views/colleges/new.html.erb
<%= render :partial => "layouts/shared/sidebar" %>

<div class="container" id="content">
  <div class="ui grid">
    <%= render :partial => "layouts/shared/notice"%>
    <div class="row">
      <h1 class="ui huge header">
        Create A College
      </h1>
    </div>
    <div class="ui divider"></div>

    <div class="row">

        <%= render 'form', college: @college %>
    </div>
  </div>
</div>

<%= link_to 'All Colleges', colleges_path, class: "ui basic button" %>

app/views/colleges/show.html.erb
<%= render :partial => "layouts/shared/sidebar" %>
<div class="column" id="content">
  <div class="ui ">
    <%= render :partial => "layouts/shared/notice" %>
    <div class="row">
      <h1 class="ui huge header">
        View College
      </h1>
    </div>
    <div class="ui divider"></div>
    <br />

    <div class="item">
      <strong>Name:</strong>
      <%= @college.name %>
    </div>

    <div class="item">
      <strong>Institution:</strong>
      <%= Institution.find(@college.institution_id).name %>
    </div>

    
    <br />
<% if current_user.admin? %>
  <%= link_to 'Edit College', edit_college_path(@college), class: "ui large button" %> |
<% end %>
<%= link_to 'All Colleges', faculties_path, class: "ui large button" %>